from tkinter import *
root = Tk()
root.geometry('200x300')
label_x = Label(text='Значення x:').place(x=20, y=20)
label_y = Label(text='Значення y:').place(x=20, y=60)
label_z = Label(text='Значення z:').place(x=20, y=100)
label_result = Label(text='Результат:').place(x=20, y=180)
entry_x = Entry()
entry_y = Entry()
entry_z = Entry()
entry_x.place(x=20, y=40)
entry_y.place(x=20, y=80)
entry_z.place(x=20, y=120)
entry_result = Entry()
entry_result.place(x=20, y=200)
def click():
    x = float(entry_x.get())
    y = float(entry_y.get())
    z = float(entry_z.get())
    t = x > 0 and (y > 0 or z < 0)
    entry_result.delete(0, END)
    entry_result.insert(0, str(t))
button = Button(command=click, width=10, text='Знайти').place(x=20, y=150)
root.mainloop()