from tkinter import *
root = Tk()
root.geometry('300x200')
label_qestion = Label(text='a*(4*b-a) =').place(x=30, y=10)
entry_answear = Entry(width=20)
entry_answear.place(x=97, y=10)
label1 = Label(text='a =').place(x=30, y=40)
label2 = Label(text='b =').place(x=30, y=70)
entry1 = Entry(width=20)
entry1.place(x=55, y=40)
entry2 = Entry(width=20)
entry2.place(x=55, y=70)
def click():
    a = float(entry1.get())
    b = float(entry2.get())
    entry_answear.delete(0, END)
    entry_answear.insert(0, a*(4*b-a))
button = Button(width=15, text='Результат', command=click).place(x=100, y=100)
root.mainloop()
